LojaDeRoupasMVC/Controllers/CamisetaController.cs
using LojaDeRoupasMVC.Models;
using LojaDeRoupasMVC.Repositories.Interfaces;
using LojaDeRoupasMVC.ViewModel;
using Microsoft.AspNetCore.Mvc;


namespace LANCHESMVC.Controllers;

public class CamisetaController : Controller
{
    private readonly ICamisetaRepository _camisetaRepository;

    public CamisetaController(ICamisetaRepository camisetaRepository)
    {
        _camisetaRepository = camisetaRepository;
    }

    public IActionResult List(string categoria)
    {
        IEnumerable<Camiseta> camisetas;
        string categoriaAtual = string.Empty;

        if (string.IsNullOrEmpty(categoria))
        {
            camisetas = _camisetaRepository.Camisetas.OrderBy(l => l.CamisetaId);
            categoriaAtual = "Todas as camisetas";
        }
        else
        {
            if (string.Equals("Camiseta Normal", categoria, StringComparison.OrdinalIgnoreCase))
            {
                camisetas = _camisetaRepository.Camisetas
                    .Where(l => l.Categoria.CategoriaNome.Equals("Camiseta Normal"))
                    .OrderBy(l => l.Nome);
            }
            else
            {
                camisetas = _camisetaRepository.Camisetas
                   .Where(l => l.Categoria.CategoriaNome.Equals("Camiseta Regata"))
                   .OrderBy(l => l.Nome);
            }
            categoriaAtual = categoria;
        }

        var camisetaVM = new CamisetaViewModel
        {
            Camisetas = camisetas,
            CategoriaAtual = categoriaAtual
        };

        return View(camisetaVM);
    }

    public IActionResult Details (int camisetaId)
    {
        var camisetas = _camisetaRepository.Camisetas.FirstOrDefault(c => c.CamisetaId == camisetaId);
        return View (camisetas);
    }

    public IActionResult Search(string searchString)
    {
        IEnumerable<Camiseta> camisetas;
        string categoriaAtual = string.Empty;

        if (string.IsNullOrEmpty(searchString))
        {
           camisetas = _camisetaRepository.Camisetas.OrderBy(c => c.CamisetaId);
            categoriaAtual = "Todas as camisetas";

        }
        else
        {
            camisetas = _camisetaRepository.Camisetas.Where(c => c.Nome.ToLower().Contains(searchString.ToLower()));

            if(camisetas.Any())
            {
                categoriaAtual = "Camisetas";
            }
            else
            {
                categoriaAtual = "Nenhuma camiseta encontrada!";
            }
        } 
        return View("~/Views/Camiseta/List.cshtml", new CamisetaViewModel
        {
            Camisetas = camisetas,
            CategoriaAtual = categoriaAtual
        });
    }

}

LojaDeRoupasMVC/Controllers/CarrinhoCompraController.cs
using LojaDeRoupasMVC.Models;
using LojaDeRoupasMVC.Repositories.Interfaces;
using LojaDeRoupasMVC.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace LojaDeRoupasMVC.Controllers;

public class CarrinhoCompraController : Controller
{
   private readonly ICamisetaRepository _camisetaRepository;
    private readonly CarrinhoCompra _carrinhoCompra;

    public CarrinhoCompraController(ICamisetaRepository camisetaRepository, CarrinhoCompra carrinhoCompra)
    {
        _camisetaRepository = camisetaRepository;
        _carrinhoCompra = carrinhoCompra;
    }

    public IActionResult Index()
    {
        var itens = _carrinhoCompra.GetCarrinhoCompraItems();
        _carrinhoCompra.CarrinhoCompraItems = itens;

        var carrinhoCompraVM = new CarrinhoCompraViewModel 
        {
            CarrinhoCompra = _carrinhoCompra,
            CarrinhoCompraTotal = _carrinhoCompra.GetCarrinhoCompraTotal()
        };



        return View(carrinhoCompraVM);
    }

    public RedirectToActionResult AdicionarItemNoCarrinhoCompra (int camisetaId)
    {
        var camisetaSelecionada = _camisetaRepository.Camisetas.FirstOrDefault(c => c.CamisetaId == camisetaId);

        if (camisetaSelecionada !=  null)
        {
            _carrinhoCompra.AdicionarAoCarrinho(camisetaSelecionada);
        }
        return RedirectToAction("Index");

    }

    public RedirectToActionResult RemoverItemDoCarrinhoCompra(int camisetaId)
    {
        var camisetaSelecionada = _camisetaRepository.Camisetas.FirstOrDefault(c => c.CamisetaId == camisetaId);

        if (camisetaSelecionada != null)
        {
            _carrinhoCompra.RemoverDoCarrinho(camisetaSelecionada);
        }
        return RedirectToAction("Index");

    }



}

LojaDeRoupasMVC/Controllers/ContatoController.cs
using Microsoft.AspNetCore.Mvc;

namespace LojaDeRoupasMVC.Controllers;

public class ContatoController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

LojaDeRoupasMVC/Views/Shared/_CamisetaResumo.cshtml
@model Camiseta

<div class="col-sm-4 col-md-4 col-lg-4">
    <p><img src="@Model.ImagemUrl" class="img-fluid"/> </p>
    <h4>
        <a asp-controller="Camiseta" asp-action="Details" asp-route-camisetaId="@Model.CamisetaId"> @Model.Nome </a>
    </h4>
    <h3>Preço: @Model.Preco</h3>
    <p>@Model.Descricao</p>

    <div>
        <p class="button">
            <a class="btn btn-primary" id="cartButton" asp-controller="CarrinhoCompra" 
            asp-action="AdicionarItemNoCarrinhoCompra" asp-route-camisetaId="@Model.CamisetaId">
            Adicionar ao Carrinho
        </a>
        </p>
    </div>

</div>

LojaDeRoupasMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LojaDeRoupasMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LojaDeRoupasMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LojaDoGalo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                            
                        <li class="nav-item">
                            
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            @await Component.InvokeAsync("CategoriaMenu")
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Contato" asp-action="Index">Contato</a>
                        </li>
                        <form class="navbar-form navbar-right" asp-controller="Camiseta" asp-action="Search" method="get">
                            <div class="form-group">
                               <input type="text" class="form-control" placeholder="Procurar produto" name="searchString"
                                       value="@ViewData["searchString"]" />
                            </div>
                        </form>
                        
                        <li class="nav-item ml-5">
                            @await Component.InvokeAsync("CarrinhoCompraResumo")
                        </li>
                        <li class="nav-item ml-5">
                            @await Html.PartialAsync("_LoginPartial");
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

  
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LojaDeRoupasMVC/Views/Shared/_ProdutosHomePartial.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Produtos em Destaque</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <style>
        .highlight-card .card-img-top {
            width: 100%;
            height: auto;
            max-height: 500px; 
            object-fit: cover;
            overflow: hidden
        }
    </style>
</head>
<body>
    <div class="container highlight-section">
        <h2 class="text-center mb-4">Produtos em Destaque</h2>   
        <div class="row">
            <div class="col-md-6">
                <div class="card highlight-card">
                    <img src="/images/camisetapreta.png" class="card-img-top img-fluid" alt="Produto 1">
                    <div class="card-body">
                        <h5 class="card-title">Camiseta Preta</h5>
                        <p class="card-text">Linda camiseta masculina.</p>
                        <a asp-controller="Camiseta" asp-action="Details" asp-route-camisetaId="1" class="btn btn-primary">Comprar</a>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card highlight-card">
                    <img src="/images/camisetapretagata.webp" class="card-img-top img-fluid" alt="Regata Preta">
                    <div class="card-body">
                        <h5 class="card-title">Regata Preta</h5>
                        <p class="card-text">Linda camiseta regata masculina.</p>
                        <a asp-controller="Camiseta" asp-action="Details" asp-route-camisetaId="4" class="btn btn-primary">Comprar</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>